# Generated by Django 6.1 on 2026-08-23 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_visit_status_antenatalvisit_appointment_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specimen_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('specimen_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('in_transit', 'In Transit'), ('received', 'Received in Lab'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='collected', max_length=20)),
                ('collection_datetime', models.DateTimeField()),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('local', 'Local'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens_collected', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens', to='clinical.order')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='patients.patient')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens_received', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens', to='clinical.visit')),
            ],
            options={
                'db_table': 'specimens',
                'ordering': ['-collection_datetime'],
                'managed': True,
            },
        ),
    ]
