# Generated by Django 6.1 on 2026-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_ernurseevaluation_pediatricassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('opd', 'Outpatient Department'), ('ipd', 'Inpatient Department'), ('er', 'Emergency Room'), ('pediatric', 'Pediatric'), ('obgyn', 'Obstetrics & Gynecology'), ('anc', 'Antenatal Care'), ('labor_delivery', 'Labor & Delivery'), ('postpartum', 'Postpartum'), ('surgery', 'Surgery'), ('telemedicine', 'Telemedicine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('opd', 'Outpatient Department'), ('ipd', 'Inpatient Department'), ('er', 'Emergency Room'), ('pediatric', 'Pediatric'), ('obgyn', 'Obstetrics & Gynecology'), ('anc', 'Antenatal Care'), ('labor_delivery', 'Labor & Delivery'), ('postpartum', 'Postpartum'), ('surgery', 'Surgery'), ('telemedicine', 'Telemedicine')], max_length=20),
        ),
    ]
