# Generated by Django 6.1 on 2026-08-28 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_alter_encounter_encounter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_visits', to='clinical.visit'),
        ),
    ]
