# Generated by Django 6.1 on 2026-09-02 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_add_visit_to_appointment'),
        ('patients', '0002_alter_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=25),
        ),
        migrations.CreateModel(
            name='CriticalResultNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent')], default='critical', max_length=20)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_notifications_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('notified_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='critical_notifications_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_notifications', to='patients.patient')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinical.diagnosticresult')),
            ],
            options={
                'db_table': 'critical_result_notifications',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
