# Generated by Django 6.1 on 2026-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_diagnosticresult_entered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='emergency_bypass_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_emergency_bypass',
            field=models.BooleanField(default=False),
        ),
    ]
