# Generated by Django 6.1 on 2026-09-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_visit_emergency_bypass_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='queue_number',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('amended', 'Amended')], default='active', max_length=20),
        ),
    ]
