# Generated by Django 6.1 on 2026-09-03 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_triagerecord_queue_number_alter_admission_status'),
        ('patients', '0003_patient_is_temporary_patient_temporary_token_and_more'),
        ('users_auth', '0004_alter_hospitalsetting_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Rule name, e.g. "Severe Hypotension"', max_length=100)),
                ('vital_sign', models.CharField(choices=[('temperature', 'Temperature'), ('heart_rate', 'Heart Rate'), ('respiratory_rate', 'Respiratory Rate'), ('blood_pressure_systolic', 'Systolic BP'), ('blood_pressure_diastolic', 'Diastolic BP'), ('oxygen_saturation', 'SpO2'), ('pain_scale', 'Pain Scale'), ('blood_glucose', 'Blood Glucose')], max_length=30)),
                ('operator', models.CharField(choices=[('lt', '<'), ('lte', '<='), ('gt', '>'), ('gte', '>='), ('eq', '='), ('between', 'Between')], max_length=10)),
                ('threshold_low', models.DecimalField(decimal_places=2, help_text='Primary threshold value', max_digits=8)),
                ('threshold_high', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound for "between" operator', max_digits=8, null=True)),
                ('suggested_acuity', models.IntegerField(choices=[(1, 'Resuscitation'), (2, 'Emergent'), (3, 'Urgent'), (4, 'Less Urgent'), (5, 'Non-Urgent')])),
                ('suggested_department', models.CharField(choices=[('ER', 'Emergency Room'), ('OPD', 'Outpatient Department'), ('IPD', 'Inpatient Department'), ('OBGYN', 'Obstetrics & Gynecology')], default='OPD', max_length=20)),
                ('priority', models.IntegerField(default=100, help_text='Evaluation order (lower = checked first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'triage_criteria',
                'ordering': ['priority', 'vital_sign'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='acuity_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='acuity_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='route_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='route_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='suggested_acuity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='suggested_department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='temporary_token',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('in_triage', 'In Triage'), ('in_progress', 'In Progress'), ('pending_registration', 'Pending Registration'), ('awaiting_reconciliation', 'Awaiting Reconciliation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=30),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('trigger_action', models.CharField(help_text='e.g. triage_submit, er_bypass, opd_to_er, admit_to_ipd', max_length=50)),
                ('metadata', models.JSONField(blank=True, help_text='Stores override reasons, routing decisions, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='users_auth.department')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions', to='patients.patient')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_to', to='users_auth.department')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions', to='clinical.visit')),
            ],
            options={
                'db_table': 'workflow_transitions',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
