# Generated by Django 6.1 on 2026-09-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_triagecriteria_visit_acuity_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenatalvisit',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antenatal_visits', to='clinical.visit'),
        ),
        migrations.AlterField(
            model_name='laborrecord',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_records', to='clinical.visit'),
        ),
        migrations.AlterField(
            model_name='pediatricassessment',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pediatric_assessments', to='clinical.visit'),
        ),
        migrations.AlterField(
            model_name='postnatalvisit',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postnatal_visits', to='clinical.visit'),
        ),
    ]
