# Generated by Django 6.1 on 2026-09-04 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_make_obgyn_pediatric_visit_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalvisit',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antenatal_visits', to='clinical.admission'),
        ),
        migrations.AddField(
            model_name='surgicalcase',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgical_cases', to='clinical.admission'),
        ),
    ]
