# Generated by Django 6.1 on 2026-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_add_admission_fk_to_surgical_antenatal'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='triage/photos/'),
        ),
    ]
