# Generated by Django 6.1 on 2026-08-28 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_alter_usersession_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(default='Jackson F. Doe Memorial Regional Referral Hospital', max_length=200)),
                ('short_name', models.CharField(default='JFD Hospital', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Hospital Management Information System', max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, default='https://jfdhospital.com/', max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_settings',
                'managed': True,
            },
        ),
    ]
