# Generated by Django 6.1 on 2026-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_hospitalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalsetting',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
