# Generated by Django 6.1 on 2026-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_alter_hospitalsetting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsetting',
            name='followup_window_days',
            field=models.IntegerField(default=30, help_text='Number of days before/after scheduled date considered inside follow-up window'),
        ),
        migrations.AddField(
            model_name='hospitalsetting',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Registration fee charged to patients at registration', max_digits=10),
        ),
    ]
