# Generated by Django 6.1 on 2026-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('waived', 'Waived'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('waived', 'Waived'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='pending', max_length=10),
        ),
    ]
