# Generated by Django 6.1 on 2026-09-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'managed': True, 'ordering': ['created_at']},
        ),
    ]
