# Generated by Django 6.1 on 2026-08-23 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('severe', 'Severe - Avoid combination'), ('moderate', 'Moderate - Monitor closely'), ('mild', 'Mild - Be aware')], max_length=10)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='pharmacy.medication')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='pharmacy.medication')),
            ],
            options={
                'db_table': 'drug_interactions',
                'managed': True,
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
    ]
