# Generated by Django 6.1 on 2026-09-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_add_drug_interaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'managed': True, 'ordering': ['medication__name']},
        ),
    ]
