# Generated by Django 6.1 on 2026-08-18 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_received_date', models.DateField(blank=True, null=True)),
                ('last_issued_date', models.DateField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('local', 'Local'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('count_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('local', 'Local'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_counts',
                'ordering': ['-count_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('system_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_count_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('dispensed', 'Dispensed'), ('expired', 'Expired'), ('damaged', 'Damaged')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('batch_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(choices=[('local', 'Local'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-performed_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('store_type', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('local', 'Local'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('local', 'Local'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='inventory.category')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_medication', models.BooleanField(default=False)),
                ('is_consumable', models.BooleanField(default=False)),
                ('is_equipment', models.BooleanField(default=False)),
                ('reorder_level', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('minimum_stock', models.IntegerField(default=0)),
                ('maximum_stock', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('local', 'Local'), ('synced', 'Synced')], default='synced', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
