# Generated by Django 6.1 on 2026-09-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': True, 'ordering': ['item__name', 'store__name']},
        ),
    ]
