# Generated by Django 6.1 on 2026-08-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
