# Generated by Django 6.1 on 2026-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='True for emergency bypass patients awaiting formal registration'),
        ),
        migrations.AddField(
            model_name='patient',
            name='temporary_token',
            field=models.CharField(blank=True, editable=False, help_text='Temporary identifier (TEMP-ER-YYYY-XXXXX)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='patientconsent',
            table='patient_consents',
        ),
    ]
