# Generated by Django 6.1 on 2026-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_is_temporary_patient_temporary_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
    ]
